#---------------------------------------------------------------------#
#     Homarr - A simple, yet powerful dashboard for your server.      #
#---------------------------------------------------------------------#
# https://homarr.dev/docs/getting-started/
services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /mnt/drive0/appdata/homarr:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=8cfabff457cac192e4ef009dac00692906dd6d6f35f150aff91705bb75f56626    
    ports:
      - '7575:7575'