services:
    qbittorrent:
        restart: unless-stopped
        privileged: false
        volumes:
            - /opt/pvr/qbittorrent:/config
            - /mnt/drive0/appdata/plex/downloads:/downloads
        environment:
            - PUID=1000
            - PGID=1000
            - VPN_ENABLED=yes
            - VPN_TYPE=openvpn
            - LAN_NETWORK=192.168.2.0/24
            - NAME_SERVERS=1.1.1.1,1.0.0.1
            - ENABLE_SSL=no
            - HEALTH_CHECK_HOST=one.one.one.one
        ports:
            - 8180:8080
        image: dyonr/qbittorrentvpn
    sonarr:
        image: linuxserver/sonarr:latest
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        volumes:
            - /opt/pvr/sonarr:/config
            - /mnt/drive0/appdata/plex/tv:/tv
            - /mnt/drive0/appdata/plex/downloads:/downloads
        ports:
            - 8989:8989
        restart: unless-stopped
    radarr:
        image: linuxserver/radarr:latest
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        volumes:
            - /opt/pvr/radarr:/config
            - /mnt/drive0/appdata/plex/movies:/movies
            - /mnt/drive0/appdata/plex/downloads:/downloads
        ports:
            - 7878:7878
        restart: unless-stopped
    jackett:
        image: linuxserver/jackett:latest
        container_name: jackett
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - AUTO_UPDATE=true
        volumes:
            - /opt/pvr/jackett:/config
            - /mnt/drive0/appdata/plex/downloads:/downloads
        ports:
            - 9117:9117
        restart: unless-stopped
    jellyfin:
      image: lscr.io/linuxserver/jellyfin:latest
      container_name: jellyfin
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Etc/UTC
        - JELLYFIN_PublishedServerUrl=http://192.168.0.5 #optional
      volumes:
        - /path/to/jellyfin/library:/config
        - /path/to/tvseries:/data/tvshows
        - /path/to/movies:/data/movies
      ports:
        - 8096:8096
        - 8920:8920 #optional
        - 7359:7359/udp #optional
        - 1900:1900/udp #optional
      restart: unless-stopped