services:
    qbittorrent:
        restart: unless-stopped
        privileged: true
        volumes:
            - /opt/pvr/qbittorrent:/config
            - /mnt/drive0/appdata/plex/downloads:/downloads
        environment:
            - PUID=1000
            - PGID=1000
            - VPN_ENABLED=yes
            - VPN_TYPE=openvpn
            - LAN_NETWORK=192.168.2.0/24
            - NAME_SERVERS=1.1.1.1,1.0.0.1
            - ENABLE_SSL=no
            - HEALTH_CHECK_HOST=one.one.one.one
        ports:
            - 8180:8080
        image: dyonr/qbittorrentvpn
    sonarr:
        image: ghcr.io/linuxserver/sonarr:latest
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        volumes:
            - /opt/pvr/sonarr:/config
            - /mnt/drive0/appdata/plex/tv:/tv
            - /mnt/drive0/appdata/plex/downloads:/downloads
        ports:
            - 8989:8989
        restart: unless-stopped
    radarr:
        image: ghcr.io/linuxserver/radarr:latest
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        volumes:
            - /opt/pvr/radarr:/config
            - /mnt/drive0/appdata/plex/movies:/movies
            - /mnt/drive0/appdata/plex/downloads:/downloads
        ports:
            - 7878:7878
        restart: unless-stopped
    jackett:
        image: ghcr.io/linuxserver/jackett:latest
        container_name: jackett
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - AUTO_UPDATE=true
        volumes:
            - /opt/pvr/jackett:/config
            - /mnt/drive0/appdata/plex/downloads:/downloads
        ports:
            - 9117:9117
        restart: unless-stopped
    overseerr:
        image: ghcr.io/linuxserver/overseerr:latest
        container_name: overseerr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        volumes:
            - /opt/pvr/overseerr:/config
        ports:
            - 5055:5055
        restart: unless-stopped